# -*- coding: utf-8 -*-
"""Solve L3 CW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fJwUCdQ2k4O2jfbx08_P0gDutUXX_XFG
"""

#task1
class MangoTree:
  def __init__(self,variety,height=1,number_of_mangoes=0):
    self.variety=variety
    self.height=height
    self.number_of_mangoes=number_of_mangoes
  def growthUpdate(self,update):
    if self.variety=="Gopalbhog":
      self.height+=update*3
      self.number_of_mangoes=self.height*10
      print(f'Variety: {self.variety}\nHeight: {self.height} meter(s)\nNumber of mangoes on the tree: {self.number_of_mangoes}')
    elif self.variety=="Amrapali":
      self.height+=update*3
      self.number_of_mangoes=self.height*15
      print(f'Variety: {self.variety}\nHeight: {self.height} meter(s)\nNumber of mangoes on the tree: {self.number_of_mangoes}')
mangoTree1= MangoTree("Gopalbhog")
# Display the details of the mango tree
print("=====================================")
print("Mango Tree Details:")
print(f"Variety: {mangoTree1.variety}")
print(f"Height: {mangoTree1.height} meter(s)")
print(f"Number of mangoes on the tree: {mangoTree1.number_of_mangoes}")
print("=====================================")
mangoTree2= MangoTree("Amrapali")
# Display the details of the mango tree
print("Mango Tree Details:")
print(f"Variety: {mangoTree2.variety}")
print(f"Height: {mangoTree2.height} meter(s)")
print(f"Number of mangoes on the tree: {mangoTree2.number_of_mangoes}")
print("=====================================")
print("Updated details after 5 years:")
mangoTree1= MangoTree("Gopalbhog")
print("=====================================")
mangoTree1.growthUpdate(5)
print("=====================================")
mangoTree2= MangoTree("Amrapali")
mangoTree2.growthUpdate(5)
print("=====================================")

#task2
class Customer:
  def __init__(self):
    self.dic={}
    self.tc=0
    self.v=0
    print("Welcome to ABC Memorial Park")
  def buyTicket(self,name,age):
    self.name=name
    self.age=age
    self.dic.update({self.name:self.age})
    if len(self.dic)<=3:
      if self.dic[name]>10:
         self.v+=100
         self.tc+=1
         print(f"Successfully purchased a ticket for {self.name}!")
      else:
        self.v+=50
        self.tc+=1
        print(f"Successfully purchased a ticket for {self.name}!")
    elif len(self.dic)>3:
      print("You can't buy more than 3 tickets")

  def showDetails(self):
    print(f'Amount of tickets:{self.tc}')
    print(f'Total price:{self.v} Taka')




print('1-------------------------')
customer1 = Customer()
print('2-------------------------')
customer1.buyTicket('Bob', 23)
customer1.buyTicket('Henry', 7)
customer1.buyTicket('Alexa', 30)
customer1.buyTicket('Jonas', 43)
print('3-------------------------')
customer1.showDetails()
print('4-------------------------')
customer2 = Customer()
print('5-------------------------')
customer2.buyTicket('Harry', 60)
customer2.buyTicket('Tomas', 28)
print('6-------------------------')
customer2.showDetails()

#task3
class GreenPhone:
  def __init__(self, model_name, android_version, num_cameras):
        self.company = "GreenPhone"
        self.model_name = model_name
        self.android_version = android_version
        self.num_cameras = num_cameras

  def showSpecification(self):
        print("Phone Company:", self.company)
        print("Model Name:", self.model_name)
        print("Android Version:", self.android_version)
        print("Number of Cameras:", self.num_cameras)

  def updatePhone(self):
    if self.model_name[0]=='A':
        if self.android_version <= 12 or self.android_version <= 13:
          self.android_version += 1
          print(f"Your phone {self.company} {self.model_name} is upgraded to Android Version: {self.android_version}.")
        else:
            print(f"Your phone {self.company} {self.model_name} is already up to date.")
    elif self.model_name[0]=='M':
         if self.android_version <= 12 or self.android_version <= 15:
            self.android_version += 1
            print(f"Your phone {self.company} {self.model_name} is upgraded to Android Version: {self.android_version}.")
         else:
              print(f"Your phone {self.company} {self.model_name} is already up to date.")
    elif self.model_name[0]=='U':
        if self.android_version <= 12 or self.android_version <= 15:
           self.android_version += 1
           print(f"Your phone {self.company} {self.model_name} is upgraded to Android Version: {self.android_version}.")
        else:
            print(f"Your phone {self.company} {self.model_name} is already up to date.")

print('1=======================')
p1 = GreenPhone('A1', 12, 3)
p2 = GreenPhone('M11', 12, 4)
p3 = GreenPhone('U20', 12, 5)
p1.showSpecification()
print('2=======================')
p2.showSpecification()
print('3=======================')
p1.updatePhone()
print('4=======================')
p1.updatePhone()
p2.updatePhone()
p3.updatePhone()
print('5=======================')
p1.updatePhone()
p2.updatePhone()
p3.updatePhone()
print('6=======================')
p2.updatePhone()
p3.updatePhone()
print('7=======================')
p1.showSpecification()
p3.showSpecification()